name: 🌐 Keep Render App Awake

on:
  schedule:
    - cron: '*/10 * * * *'  # every 10 minutes UTC
  workflow_dispatch:       # allows manual run

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: ⏰ Ping Render App
        run: curl --silent --show-error --fail https://erpmanager.onrender.com || echo "❌ Ping failed"
