# Generated by Django 5.2 on 2025-04-05 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_order_date_order_order_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="bill_file",
        ),
    ]
