# Generated by Django 5.2 on 2025-04-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_remove_order_bill_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="customer_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
