# Generated by Django 5.2 on 2025-04-05 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_customer_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="selling_price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
