# Generated by Django 5.2 on 2025-04-06 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_orderitem_selling_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
